name: Input Workflow

on:
  push:
    branches:
      - dev

jobs:
  run-main-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Set File Path Input
        id: set_file_path
        run: echo "::set-output name=file_path::${{ github.workspace }}/test.txt"

      - name: Run Main Workflow in main-repo
        uses: anujnarayan23/main/.github/workflows/main.yml@dev
        with:
          file_path: ${{ steps.set_file_path.outputs.file_path }}
