# This is BU repo

name: Input Workflow

on:
  push:
    branches:
      - dev

jobs:
  run-main-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Main Workflow in main-repo
        uses: actions/checkout@v2
      - name: Set File Path Input
        id: set_file_path
        run: echo "::set-output name=file_path::${{ github.workspace }}/test.txt"
      - name: Run Main Workflow in main-repo
        uses: actions/checkout@v2
        with:
          repository: anujnarayan23/main  # Specify the target repository
          ref: dev  # Replace 'dev' with the actual branch or commit reference
          uses: main/.github/workflows/main-workflow.yml
          file_path: ${{ steps.set_file_path.outputs.file_path }}
