# This is BU repo

name: Input Workflow

on:
  push:
    branches:
      - dev

jobs:
  call-workflow-passing-data:
    uses: anujnarayan23/main/.github/workflows/main-workflow.yml@dev
  run-main-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Main Workflow in main-repo
        uses: actions/checkout@v2
      - name: Set File Path Input
        id: set_file_path
        run: echo "::set-output name=file_path::${{ github.workspace }}/test.txt"
        
