name: Input Workflow

on:
  push:
    branches:
      - dev

jobs:
  run-main-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Set File Path Input
        id: set_file_path
        run: echo "::set-output name=file_path::${{ github.workspace }}/test.txt"
      
      - name: Trigger Main Workflow in main-repo
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await octokit.actions.createWorkflowDispatch({
              owner: 'anujnarayan23',
              repo: 'main',
              ref: 'dev',
              workflow: 'main-workflow.yml',
              inputs: {
                file_path: ${{ steps.set_file_path.outputs.file_path }}
              }
            });
            console.log(response);
