# This is BU repo

name: Input Workflow

on:
  workflow_run:
    workflows: ["Main Workflow"]
    types:
      - completed
  
jobs:
  call-workflow-passing-data:
    uses: main/.github/workflows/main-workflow.yml@dev
  run-main-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Set File Path Input
        id: set_file_path
        run: echo "::set-output name=file_path::${{ github.workspace }}/test.txt"
