# This is the basic wokfow to showcase the use of Reusable Workflow

name: Reusable Workflow user test

on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Trigger Main Workflow in main-repo
        uses: actions/checkout@v2
      - name: Set File Path Input
        id: set_file_path
        run: echo "::set-output name=file_path::${{ github.workspace }}/test.txt"

  docker:
    uses: anujnarayan23/main/.github/workflows/main.yml@dev
    with:
      file_path: ${{ steps.set_file_path.outputs.file_path }}
#      image_name: my-app
 #     tag: $GITHUB_RUN_NUMBER
 #   secrets:
 #     registry_username: ${{secrets.REGISTRY_USERNAME}}
 #     registry_password: ${{secrets.REGISTRY_PASSWORD}}
